### PR TITLE
Fix To Allow Android To Work Out Of The Box

### PR DESCRIPTION
**Pull request by mcmah309**
These changes allow the android to work out of the box.

A `llama.cpp` update was needed to bypass this llama issue https://github.com/ggerganov/llama.cpp/issues/5537

Command use to update  `llama.cpp`: `flutter pub run ffigen`

### CODE REVIEW

**Comment by netdur** [comment]
@danemadsen ^^

**Comment by danemadsen** [comment]
> @danemadsen ^^

Ahh yeah I forgot to PR the update to llama.cpp

**Comment by netdur** [comment]
@danemadsen what do you recommend, does PR https://github.com/netdur/llama_cpp_dart/pull/23 also resolve this workaround? or should I merge both?

**Comment by danemadsen** [comment]
> @danemadsen what do you recommend, does PR https://github.com/netdur/llama_cpp_dart/pull/23 also resolve this workaround? or should I merge both?

Yeah PR #23 does the same as this it just doesn't update the bindings. You can merge mine, merge both, it doesn't really matter

**Pull request merged**
