### PR TITLE
Use package:typed_isolate for easier isolate management

### PR DESCRIPTION
**Pull request by Levi-Lesches**
Hi @netdur! I saw [your comment on Reddit](https://www.reddit.com/r/dartlang/comments/1els4yu/comment/ligvh7x/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) about isolates, and I saw [a reply](https://www.reddit.com/r/dartlang/comments/1els4yu/comment/likymkw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) offering to rewrite that part with [`package:actors`](https://pub.dev/packages/actors), so as author of [`package:typed_isolate`](https://pub.dev/packages/typed_isolate) I thought I'd step in and give it a shot. 

Basically, instead of managing the main isolate and model isolate in one class, I created three files: 
- isolate_types.dart: defines the payloads sent back and forth between the two isolates
- isolate_parent.dart: an object that lives in the main isolate that is responsible for communicating with the model isolate
- isolate_child.dart: a new isolate to hold the model and communicate back with the parent

I wasn't sure if you were using to/from JSON for anything else, but if not, you can remove those too. Feel free to ignore this, but hopefully it makes your code clearer! I'm also looking for feedback for the package so if you see anything you wish were different please let me know!

### CODE REVIEW

**Comment by netdur** [comment]
Thank you @Levi-Lesches I am in middle of updating package with llama.cpp I will review your improvements

**Comment by netdur** [comment]
@Levi-Lesches I've pushed my work-in-progress changes to the dev branch, primarily focusing on sampler implementations. Your PR should be compatible with minimal adjustments needed. Could you please review and confirm everything aligns properly? Thank you!

**Comment by Levi-Lesches** [comment]
@netdur I merged and updated to the best of my understanding, but granted, I'm just filling in missing context from nearby code. I left three TODO comments explaining where some fields were removed and that previous code is no longer compatible but I assume that's intentional and you have a replacement. 

Overall, you'll need to review and test to make sure I got the Llama-specific parts right, but yes, this parent/child relationship should work for your project.

**Comment by netdur** [comment]
@Levi-Lesches I have merged your code, thank you
I have implemented missing functions, you can now resold todo list
can you make an example use?

**Comment by Levi-Lesches** [comment]
Sorry, I'm not really knowledgeable on LLMs and Llama or how exactly your app is meant to be tested. I just wanted to help make your isolate code simpler for future use. 

If you have any more isolate-related questions, feel free to reach out again though!

**Pull request merged**
