### PR TITLE
support for building llama.cpp .so / dll

### PR DESCRIPTION
**Pull request by danemadsen**
Not quite working yet but close. 
Currently working for linux only

### CODE REVIEW

**Comment by netdur** [comment]
let me know once it is done, I will work on iOS / macos part, also clean up any leftovers codes or ide settings

**Comment by danemadsen** [comment]
> let me know once it is done, I will work on iOS / macos part, also clean up any leftovers codes or ide settings

I have windows and linux working now, ill let you know once i get android working.

BTW i changed the llama.cpp repo to the one managed by me as im currently relying on a bugfix ive submitted to llama.cpp that hasnt been merged yet (https://github.com/ggerganov/llama.cpp/pull/5256). You can chaneg it back to llama.cpp mainline once thats merged

**Comment by danemadsen** [comment]
@netdur ok ready to merge now android, linux and windows are now working

**Comment by danemadsen** [comment]
@netdur ???

**Comment by netdur** [comment]
I apologize for delay, got covid, I will merge as soon as i can test it.

**Comment by danemadsen** [comment]
> I apologize for delay, got covid, I will merge as soon as i can test it.

No problem, just wasn't sure if you'd seen it or not

**Comment by netdur** [comment]
I'm still stick, I will accept to not cause further delays

**Pull request merged**
